### ISSUE TITLE
build broken by openshift/api tag deletion

### ISSUE THREAD

**Issue by cgwalters** [openshift/ci-tools#414]
We currently pin a now-deleted `v3.9.1` tag which was apparently deleted: https://github.com/openshift/api/issues/456

I tried to fix this up but ended up in go mod hell, not quite sure what was going on.

**Comment by petr-muller** [comment]
Our automation does not interact with GH tags in any way. I believe I saw a Slack convo about this topic with @smarterclayton involved?

**Comment by cgwalters** [comment]
> Our automation does not interact with GH tags in any way. 

The `go.mod` says:

`	github.com/openshift/api v3.9.1-0.20190725193935-b7d4eb0fa1e0+incompatible`

But that `v3.9.1` tag no longer exists:

```
walters@toolbox ~/s/g/o/ci-tools> make build
go build ./cmd/...
go: github.com/openshift/api@v3.9.1-0.20190725193935-b7d4eb0fa1e0+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
make: *** [Makefile:7: build] Error 1
walters@toolbox ~/s/g/o/ci-tools> 
```

**Comment by stlaz** [comment]
The issue is about this repository being broken, not the actual automation. You can't build using `make build` (if you think you can, try running `go clean -modcache && make build`). I overcame certain problems trying to fix this for you, but eventually got stuck with some ambiguous Azure imports somewhere deep in kube, flipped the table and decided to leave that up to you.

You should also decide whether you want to keep your `vendor/` directory as you're not currently using it (at least when building with go 1.13).
